/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/sprirals/mergesort/implementations/nim/nimcache/mergesort.o /home/sprirals/mergesort/implementations/nim/nimcache/mergesort.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <math.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tySequence_qwqHTkRvwhrRyENtudHQ7g tySequence_qwqHTkRvwhrRyENtudHQ7g;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
N_NIMCALL(NI, customRandom_hL1pjrd9a39bLpViPbyubbkw)(NI x);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_NIMCALL(void, Marker_tySequence_qwqHTkRvwhrRyENtudHQ7g)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_Q5DCSrQVr8cKnL8Qg4cLAw_5)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_NIMCALL(NI, paramCount_T74rCHY8RMV0X07YnKmggw)(void);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, paramStr_eYicl3uwirn1ppNz7OCowg)(NI i);
N_NIMCALL(tySequence_qwqHTkRvwhrRyENtudHQ7g*, newSeq_vg7LhJDfsuQYl9cZfOCH1Fw)(NI len);
N_NIMCALL(NimStringDesc*, dollar__H9byP9au7Ewl1LWJ70fLKs7Q)(tySequence_qwqHTkRvwhrRyENtudHQ7g* x);
N_NIMCALL(NimStringDesc*, collectionToString_9aCCpFn3xaLLHw6Vu0pZCqQ)(tySequence_qwqHTkRvwhrRyENtudHQ7g* x, NimStringDesc* b, NimStringDesc* e);
N_NIMCALL(void, mergeSort_EAYKEBDM9ckXzpR5ucHn01Q)(NI* a, NI aLen_0);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, mergeSort_8RAoQUHzdWV9aUKOG0Klpyw)(NI* a, NI aLen_0, NI* b, NI bLen_0, NI left, NI right);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NIMCALL(void, merge_NGKoNwOaqgSIybLbRS9bCXA)(NI* a, NI aLen_0, NI* b, NI bLen_0, NI left, NI middle, NI right);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, mergesortDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
NI n_Mqvio7xlEul3EVB2Op4Frg;
NI niters_jJ0n14gElE6FJCG44BHUbQ;
tySequence_qwqHTkRvwhrRyENtudHQ7g* a_FLHWaIDjbHWlVIS3ZElqfg;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_qwqHTkRvwhrRyENtudHQ7g_;
NI iter_TgMhAKokwwNU1VkoCMfbgA;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
NI i_kEqesASafd3b9aq6bU69ahuA;

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(NI, customRandom_hL1pjrd9a39bLpViPbyubbkw)(NI x) {
	NI result;
	NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_2;
	NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_3;
	NF T1_;
	NF T2_;
	NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_4;
	nimfr_("customRandom", "mergesort.nim");
{	result = (NI)0;
	nimln_(59, "mergesort.nim");
	TM_Q5DCSrQVr8cKnL8Qg4cLAw_2 = mulInt(x, x);
	TM_Q5DCSrQVr8cKnL8Qg4cLAw_3 = mulInt((NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_2), x);
	T1_ = (NF)0;
	T1_ = cos(((NF) (x)));
	T2_ = (NF)0;
	T2_ = cos(((NF) (x)));
	TM_Q5DCSrQVr8cKnL8Qg4cLAw_4 = modInt(((NI) (((NF)(((NF)(((NF) ((NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_3)))) * (NF)(T1_))) * (NF)(T2_)))), ((NI) 1000000));
	result = ((NI) ((NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_4)));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tySequence_qwqHTkRvwhrRyENtudHQ7g)(void* p, NI op) {
	tySequence_qwqHTkRvwhrRyENtudHQ7g* a;
	NI T1_;
	a = (tySequence_qwqHTkRvwhrRyENtudHQ7g*)p;
	T1_ = (NI)0;
}
static N_NIMCALL(void, TM_Q5DCSrQVr8cKnL8Qg4cLAw_5)(void) {
	nimGCvisit((void*)a_FLHWaIDjbHWlVIS3ZElqfg, 0);
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(void, merge_NGKoNwOaqgSIybLbRS9bCXA)(NI* a, NI aLen_0, NI* b, NI bLen_0, NI left, NI middle, NI right) {
	NI leftLen;
	NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_9;
	NI rightLen;
	NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_10;
	NI l;
	NI r;
	NI i_3;
	nimfr_("merge", "mergesort.nim");
	nimln_(10, "mergesort.nim");
	TM_Q5DCSrQVr8cKnL8Qg4cLAw_9 = subInt(middle, left);
	leftLen = (NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_9);
	nimln_(11, "mergesort.nim");
	TM_Q5DCSrQVr8cKnL8Qg4cLAw_10 = subInt(right, middle);
	rightLen = (NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_10);
	nimln_(13, "mergesort.nim");
	l = ((NI) 0);
	nimln_(14, "mergesort.nim");
	r = leftLen;
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(16, "mergesort.nim");
		colontmp_ = subInt(middle, 1);
		nimln_(1986, "system.nim");
		res = left;
		{
			nimln_(1987, "system.nim");
			while (1) {
				NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_11;
				NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_12;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(1988, "system.nim");
				i = res;
				if ((NU)(l) >= (NU)(bLen_0)) raiseIndexError();
				nimln_(17, "mergesort.nim");
				if ((NU)(i) >= (NU)(aLen_0)) raiseIndexError();
				b[l] = a[i];
				nimln_(18, "mergesort.nim");
				TM_Q5DCSrQVr8cKnL8Qg4cLAw_11 = addInt(l, ((NI) 1));
				l = (NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_11);
				nimln_(1989, "system.nim");
				TM_Q5DCSrQVr8cKnL8Qg4cLAw_12 = addInt(res, ((NI) 1));
				res = (NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_12);
			} LA3: ;
		}
	}
	{
		NI i_2;
		NI colontmp__2;
		NI res_2;
		i_2 = (NI)0;
		colontmp__2 = (NI)0;
		nimln_(19, "mergesort.nim");
		colontmp__2 = subInt(right, 1);
		nimln_(1986, "system.nim");
		res_2 = middle;
		{
			nimln_(1987, "system.nim");
			while (1) {
				NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_13;
				NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_14;
				if (!(res_2 <= colontmp__2)) goto LA6;
				nimln_(1988, "system.nim");
				i_2 = res_2;
				if ((NU)(r) >= (NU)(bLen_0)) raiseIndexError();
				nimln_(20, "mergesort.nim");
				if ((NU)(i_2) >= (NU)(aLen_0)) raiseIndexError();
				b[r] = a[i_2];
				nimln_(21, "mergesort.nim");
				TM_Q5DCSrQVr8cKnL8Qg4cLAw_13 = addInt(r, ((NI) 1));
				r = (NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_13);
				nimln_(1989, "system.nim");
				TM_Q5DCSrQVr8cKnL8Qg4cLAw_14 = addInt(res_2, ((NI) 1));
				res_2 = (NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_14);
			} LA6: ;
		}
	}
	nimln_(23, "mergesort.nim");
	l = ((NI) 0);
	nimln_(24, "mergesort.nim");
	r = leftLen;
	nimln_(25, "mergesort.nim");
	i_3 = left;
	{
		nimln_(27, "mergesort.nim");
		while (1) {
			NIM_BOOL T9_;
			NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_15;
			NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_18;
			T9_ = (NIM_BOOL)0;
			T9_ = (l < leftLen);
			if (!(T9_)) goto LA10_;
			TM_Q5DCSrQVr8cKnL8Qg4cLAw_15 = addInt(leftLen, rightLen);
			T9_ = (r < (NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_15));
			LA10_: ;
			if (!T9_) goto LA8;
			nimln_(28, "mergesort.nim");
			{
				NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_16;
				if ((NU)(l) >= (NU)(bLen_0)) raiseIndexError();
				if ((NU)(r) >= (NU)(bLen_0)) raiseIndexError();
				if (!(b[l] < b[r])) goto LA13_;
				if ((NU)(i_3) >= (NU)(aLen_0)) raiseIndexError();
				nimln_(29, "mergesort.nim");
				if ((NU)(l) >= (NU)(bLen_0)) raiseIndexError();
				a[i_3] = b[l];
				nimln_(30, "mergesort.nim");
				TM_Q5DCSrQVr8cKnL8Qg4cLAw_16 = addInt(l, ((NI) 1));
				l = (NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_16);
			}
			goto LA11_;
			LA13_: ;
			{
				NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_17;
				if ((NU)(i_3) >= (NU)(aLen_0)) raiseIndexError();
				nimln_(32, "mergesort.nim");
				if ((NU)(r) >= (NU)(bLen_0)) raiseIndexError();
				a[i_3] = b[r];
				nimln_(33, "mergesort.nim");
				TM_Q5DCSrQVr8cKnL8Qg4cLAw_17 = addInt(r, ((NI) 1));
				r = (NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_17);
			}
			LA11_: ;
			nimln_(34, "mergesort.nim");
			TM_Q5DCSrQVr8cKnL8Qg4cLAw_18 = addInt(i_3, ((NI) 1));
			i_3 = (NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_18);
		} LA8: ;
	}
	{
		nimln_(36, "mergesort.nim");
		while (1) {
			NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_19;
			NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_20;
			if (!(l < leftLen)) goto LA17;
			if ((NU)(i_3) >= (NU)(aLen_0)) raiseIndexError();
			nimln_(37, "mergesort.nim");
			if ((NU)(l) >= (NU)(bLen_0)) raiseIndexError();
			a[i_3] = b[l];
			nimln_(38, "mergesort.nim");
			TM_Q5DCSrQVr8cKnL8Qg4cLAw_19 = addInt(l, ((NI) 1));
			l = (NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_19);
			nimln_(39, "mergesort.nim");
			TM_Q5DCSrQVr8cKnL8Qg4cLAw_20 = addInt(i_3, ((NI) 1));
			i_3 = (NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_20);
		} LA17: ;
	}
	{
		nimln_(40, "mergesort.nim");
		while (1) {
			NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_21;
			NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_22;
			NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_23;
			TM_Q5DCSrQVr8cKnL8Qg4cLAw_21 = addInt(leftLen, rightLen);
			if (!(r < (NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_21))) goto LA19;
			if ((NU)(i_3) >= (NU)(aLen_0)) raiseIndexError();
			nimln_(41, "mergesort.nim");
			if ((NU)(r) >= (NU)(bLen_0)) raiseIndexError();
			a[i_3] = b[r];
			nimln_(42, "mergesort.nim");
			TM_Q5DCSrQVr8cKnL8Qg4cLAw_22 = addInt(r, ((NI) 1));
			r = (NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_22);
			nimln_(43, "mergesort.nim");
			TM_Q5DCSrQVr8cKnL8Qg4cLAw_23 = addInt(i_3, ((NI) 1));
			i_3 = (NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_23);
		} LA19: ;
	}
	popFrame();
}

N_NIMCALL(void, mergeSort_8RAoQUHzdWV9aUKOG0Klpyw)(NI* a, NI aLen_0, NI* b, NI bLen_0, NI left, NI right) {
	NI middle;
	NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_7;
	NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_8;
	nimfr_("mergeSort", "mergesort.nim");
{	nimln_(46, "mergesort.nim");
	{
		NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_6;
		TM_Q5DCSrQVr8cKnL8Qg4cLAw_6 = subInt(right, left);
		if (!((NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_6) <= ((NI) 1))) goto LA3_;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(48, "mergesort.nim");
	TM_Q5DCSrQVr8cKnL8Qg4cLAw_7 = addInt(left, right);
	TM_Q5DCSrQVr8cKnL8Qg4cLAw_8 = divInt((NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_7), ((NI) 2));
	middle = (NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_8);
	nimln_(49, "mergesort.nim");
	mergeSort_8RAoQUHzdWV9aUKOG0Klpyw(a, aLen_0, b, bLen_0, left, middle);
	nimln_(50, "mergesort.nim");
	mergeSort_8RAoQUHzdWV9aUKOG0Klpyw(a, aLen_0, b, bLen_0, middle, right);
	nimln_(51, "mergesort.nim");
	merge_NGKoNwOaqgSIybLbRS9bCXA(a, aLen_0, b, bLen_0, left, middle, right);
	}BeforeRet_: ;
	popFrame();
}

N_NIMCALL(void, mergeSort_EAYKEBDM9ckXzpR5ucHn01Q)(NI* a, NI aLen_0) {
	tySequence_qwqHTkRvwhrRyENtudHQ7g* b;
	nimfr_("mergeSort", "mergesort.nim");
	nimln_(54, "mergesort.nim");
	b = newSeq_vg7LhJDfsuQYl9cZfOCH1Fw(((NI)chckRange(aLen_0, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(55, "mergesort.nim");
	mergeSort_8RAoQUHzdWV9aUKOG0Klpyw(a, aLen_0, b->data, b->Sup.len, ((NI) 0), aLen_0);
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(276, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(378, "system.nim");
		nimln_(276, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(277, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(278, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(279, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(378, "system.nim");
		nimln_(279, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(280, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(281, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(282, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(283, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_mathDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_timesDatInit000();
	stdlib_posixDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	mergesortDatInit000();
	stdlib_mathInit000();
	stdlib_parseutilsInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_timesInit000();
	stdlib_posixInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("mergesort", "mergesort.nim");
nimRegisterGlobalMarker(TM_Q5DCSrQVr8cKnL8Qg4cLAw_5);
	nimln_(64, "mergesort.nim");
	n_Mqvio7xlEul3EVB2Op4Frg = ((NI) 20);
	nimln_(65, "mergesort.nim");
	niters_jJ0n14gElE6FJCG44BHUbQ = ((NI) 1);
	nimln_(68, "mergesort.nim");
	{
		NI T3_;
		NimStringDesc* T6_;
		T3_ = (NI)0;
		T3_ = paramCount_T74rCHY8RMV0X07YnKmggw();
		if (!(((NI) 0) < T3_)) goto LA4_;
		nimln_(69, "mergesort.nim");
		T6_ = (NimStringDesc*)0;
		T6_ = paramStr_eYicl3uwirn1ppNz7OCowg(((NI) 1));
		n_Mqvio7xlEul3EVB2Op4Frg = nsuParseInt(T6_);
	}
	LA4_: ;
	nimln_(71, "mergesort.nim");
	{
		NI T9_;
		NimStringDesc* T12_;
		T9_ = (NI)0;
		T9_ = paramCount_T74rCHY8RMV0X07YnKmggw();
		if (!(((NI) 1) < T9_)) goto LA10_;
		nimln_(72, "mergesort.nim");
		T12_ = (NimStringDesc*)0;
		T12_ = paramStr_eYicl3uwirn1ppNz7OCowg(((NI) 2));
		niters_jJ0n14gElE6FJCG44BHUbQ = nsuParseInt(T12_);
	}
	LA10_: ;
	{
		NI colontmp_;
		NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_24;
		NI res;
		colontmp_ = (NI)0;
		nimln_(74, "mergesort.nim");
		TM_Q5DCSrQVr8cKnL8Qg4cLAw_24 = subInt(niters_jJ0n14gElE6FJCG44BHUbQ, ((NI) 1));
		colontmp_ = (NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_24);
		nimln_(1986, "system.nim");
		res = ((NI) 0);
		{
			nimln_(1987, "system.nim");
			while (1) {
				NimStringDesc* T19_;
				NimStringDesc* T20_;
				NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_27;
				if (!(res <= colontmp_)) goto LA15;
				nimln_(1988, "system.nim");
				iter_TgMhAKokwwNU1VkoCMfbgA = res;
				nimln_(76, "mergesort.nim");
				asgnRefNoCycle((void**) (&a_FLHWaIDjbHWlVIS3ZElqfg), newSeq_vg7LhJDfsuQYl9cZfOCH1Fw(((NI)chckRange(n_Mqvio7xlEul3EVB2Op4Frg, ((NI) 0), ((NI) IL64(9223372036854775807))))));
				{
					NI colontmp__2;
					NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_25;
					NI res_2;
					i_kEqesASafd3b9aq6bU69ahuA = 0;
					colontmp__2 = (NI)0;
					nimln_(77, "mergesort.nim");
					TM_Q5DCSrQVr8cKnL8Qg4cLAw_25 = subInt(n_Mqvio7xlEul3EVB2Op4Frg, ((NI) 1));
					colontmp__2 = (NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_25);
					nimln_(1986, "system.nim");
					res_2 = ((NI) 0);
					{
						nimln_(1987, "system.nim");
						while (1) {
							NI TM_Q5DCSrQVr8cKnL8Qg4cLAw_26;
							if (!(res_2 <= colontmp__2)) goto LA18;
							nimln_(1988, "system.nim");
							i_kEqesASafd3b9aq6bU69ahuA = res_2;
							if ((NU)(i_kEqesASafd3b9aq6bU69ahuA) >= (NU)(a_FLHWaIDjbHWlVIS3ZElqfg->Sup.len)) raiseIndexError();
							nimln_(78, "mergesort.nim");
							a_FLHWaIDjbHWlVIS3ZElqfg->data[i_kEqesASafd3b9aq6bU69ahuA] = customRandom_hL1pjrd9a39bLpViPbyubbkw(i_kEqesASafd3b9aq6bU69ahuA);
							nimln_(1989, "system.nim");
							TM_Q5DCSrQVr8cKnL8Qg4cLAw_26 = addInt(res_2, ((NI) 1));
							res_2 = (NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_26);
						} LA18: ;
					}
				}
				nimln_(80, "mergesort.nim");
				T19_ = (NimStringDesc*)0;
				T19_ = dollar__H9byP9au7Ewl1LWJ70fLKs7Q(a_FLHWaIDjbHWlVIS3ZElqfg);
				printf("%s\012", T19_? (T19_)->data:"nil");
				fflush(stdout);
				nimln_(81, "mergesort.nim");
				mergeSort_EAYKEBDM9ckXzpR5ucHn01Q(a_FLHWaIDjbHWlVIS3ZElqfg->data, a_FLHWaIDjbHWlVIS3ZElqfg->Sup.len);
				nimln_(82, "mergesort.nim");
				T20_ = (NimStringDesc*)0;
				T20_ = dollar__H9byP9au7Ewl1LWJ70fLKs7Q(a_FLHWaIDjbHWlVIS3ZElqfg);
				printf("%s\012", T20_? (T20_)->data:"nil");
				fflush(stdout);
				nimln_(1989, "system.nim");
				TM_Q5DCSrQVr8cKnL8Qg4cLAw_27 = addInt(res, ((NI) 1));
				res = (NI)(TM_Q5DCSrQVr8cKnL8Qg4cLAw_27);
			} LA15: ;
		}
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, mergesortDatInit000)(void) {
NTI_qwqHTkRvwhrRyENtudHQ7g_.size = sizeof(tySequence_qwqHTkRvwhrRyENtudHQ7g*);
NTI_qwqHTkRvwhrRyENtudHQ7g_.kind = 24;
NTI_qwqHTkRvwhrRyENtudHQ7g_.base = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
NTI_qwqHTkRvwhrRyENtudHQ7g_.flags = 2;
NTI_qwqHTkRvwhrRyENtudHQ7g_.marker = Marker_tySequence_qwqHTkRvwhrRyENtudHQ7g;
}

